### PR TITLE
add initial implementation

### PR DESCRIPTION
**Pull request by InfernoFeniks**
Everything is implemented except with cascading replicas

### CODE REVIEW

**Comment by kvendingoldo** [comment]
Wow! Looks perfect! I will make the review tomorrow morning.

**Comment by kvendingoldo** [comment]
Looks perfect. Please, solve two highlights and I will merge it after that. Do you want to maintain this repo in the future?

**Comment by InfernoFeniks** [comment]
What are the two highlights ?

primary maintainer? I can help, but with a delay, because I have little time

**Comment by InfernoFeniks** [comment]
> @InfernoFeniks sorry, I forget to click on "submit" button :)

It happens.))

**Review by kvendingoldo — APPROVED** [review]
LGTM!

**Comment by kvendingoldo** [comment]
@InfernoFeniks I've invited you to this repo as maintainer too) Thank your for these efforts

**Pull request merged**
